---
deprecations:
  - The ``[ilo]/clean_priority_erase_devices`` configuration option is
    deprecated and will be removed in the Ocata cycle. Please use the
    ``[deploy]/erase_devices_priority`` option instead.
