---
features:
  - Port group information (``mode`` and ``properties`` fields)
    is now passed to Neutron via the port's ``binding:profile`` field.
    This allows an ML2 driver to configure the port bonding automatically.
