---
fixes:
  - Fixed a bug that was causing grub installation failure. If the disk
    was already coming with a partition table, the conductor was not able
    to wipe it properly and the new partition table would conflict with
    the old one. The issue was only impacting new nodes and installations
    with automated_clean disabled in the configuration.
    A disk instance without preserve_ephemeral is now purged before new deployment.
    See https://bugs.launchpad.net/ironic-lib/+bug/1550604
