var errorCode_zh_CN = {
    //-------------------自定义---------------------------------------------
    "0": "成功",
    "1204": "eSight连接失败，请重试。",
    "-331": "eSight连接失败，请重试。",
    "201": "查询或删除失败，待操作对象不存在",

    "149201": "License数量不足。",

    "-99999": "操作失败：未知错误",
    "-90001": "系统内部错误，请先初始化", //系统内部错误 9xxxx
    "-90002": "请先配置eSight",
    "-90003": "登录状态失效请重新登录vCenter",
    "-90004": "当前没有失败任务可被清除",
    "-90005": "eSight用户名或者密码错误",
    "-80009": "连接当前eSight失败:访问eSight服务器时发生错误。", //网络错误  8xxxx
    "-80010": "连接当前eSight失败:连接到eSight服务器时发生错误, 由于目标机积极拒绝。",
    "-80011": "没有找到对应的eSight",
    "-81001": "连接当前eSight失败:连接到eSight服务器时发生错误, 出现网络错误",
    "-70001": "数据库没有找到对应的数据。", //数据库没有找到对应的数据。[{0}]  //数据库错误 7xxxx
    "-50400": "连接当前eSight失败:BadRequest 指示服务器未能识别请求。",
    "-50401": "连接当前eSight失败:Unauthorized 指示请求的资源要求身份验证。WWW-Authenticate 头包含如何执行身份验证的详细信息。",
    "-50402": "连接当前eSight失败:保留 PaymentRequired 以供将来使用。",
    "-50403": "连接当前eSight失败:Forbidden 指示服务器拒绝满足请求。",
    "-50404": "连接当前eSight失败:NotFound 指示请求的资源不在服务器上。",
    "-50405": "连接当前eSight失败:MethodNotAllowed 指示请求的资源上不允许请求方法（POST 或 GET）。",
    "-50406": "连接当前eSight失败:NotAcceptable 指示客户端已用 Accept 头指示将不接受资源的任何可用表示形式。",
    "-50407": "连接当前eSight失败:ProxyAuthenticationRequired 指示请求的代理要求身份验证。Proxy-authenticate 头包含如何执行身份验证的详细信息。",
    "-50408": "连接当前eSight失败:RequestTimeout 指示客户端没有在服务器期望请求的时间内发送请求。",
    "-50409": "连接当前eSight失败:Conflict 指示由于服务器上的冲突而未能执行请求。",
    "-50410": "连接当前eSight失败:Gone 指示请求的资源不再可用。",
    "-50411": "连接当前eSight失败:LengthRequired 指示缺少必需的 Content-length 头。",
    "-50412": "连接当前eSight失败:PreconditionFailed 指示为此请求设置的条件失败，且无法执行此请求。条件是用条件请求标头（如 If-Match、If-None-Match 或 If-Unmodified-Since）设置的。",
    "-50413": "连接当前eSight失败:RequestEntityTooLarge 指示请求太大，服务器无法处理。",
    "-50414": "连接当前eSight失败:RequestUriTooLong 指示 URI 太长。",
    "-50415": "连接当前eSight失败:UnsupportedMediaType 指示请求是不支持的类型。",
    "-50416": "连接当前eSight失败:RequestedRangeNotSatisfiable 指示无法返回从资源请求的数据范围，因为范围的开头在资源的开头之前，或因为范围的结尾在资源的结尾之后。",
    "-50417": "连接当前eSight失败:ExpectationFailed 指示服务器未能符合 Expect 头中给定的预期值。",
    "-50500": "连接当前eSight失败:InternalServerError 指示服务器上发生了一般错误。",
    "-50501": "连接当前eSight失败:NotImplemented 指示服务器不支持请求的函数。",
    "-50502": "连接当前eSight失败:BadGateway 指示中间代理服务器从另一代理或原始服务器接收到错误响应。",
    "-50503": "连接当前eSight失败:ServiceUnavailable 指示服务器暂时不可用，通常是由于过多加载或维护。",
    "-50504": "连接当前eSight失败:GatewayTimeout 指示中间代理服务器在等待来自另一个代理或原始服务器的响应时已超时。",
    "-50505": "连接当前eSight失败:HttpVersionNotSupported 指示服务器不支持请求的 HTTP 版本。",
    "firmware.error.51001": "参数不合法。",
	"10000": "eSight返回，发生内部错误。",
	"firmware.error.10000": "eSight返回，发生内部错误。",
	"deploy.error.10000": "eSight返回，发生内部错误。",
	"firmware.error.99998": "eSight返回，上传升级包文件不存在。",
	"deploy.error.99998": "eSight返回，上传软件源文件不存在。",
	"firmware.error.500223": "eSight返回，描述的固件类型与实际固件类型不匹配",
	"firmware.error.400100": "eSight返回，操作失败，升级包校验失败",
	"firmware.error.300509": "eSight返回，操作失败，查询列表失败",
	"deploy.error.200008": "eSight返回，上传软件源失败，eSight剩余空间不足5G。",
	"deploy.error.1100": "eSight返回，上传文件失败,可能因为网络异常或者管理用户认证失败导致设备管理异常。",
	"deploy.error.52105": "eSight返回，任务正在运行。",	
	"deploy.error.52104": "eSight返回，删除任务失败，系统错误。",	
	"device.error.-1": "eSight返回，由于参数错误(DN)，无法查询服务器详细信息。",


    //-------------------自定义---------------------------------------------
    //------------------固件升级-------------
    "firmware.error.200150": "没有操作权限。",
    "firmware.error.200100": "升级包描述文件不存在。",
    "firmware.error.200101": "升级包描述文件解析失败。",
    "firmware.error.200102": "升级模块不支持升级。",
    "firmware.error.200103": "该升级包不包括设备型号。",
    "firmware.error.200105": "固件生效策略不支持。",
    "firmware.error.200106": "固件升级文件校验类型不合法。",
    "firmware.error.200107": "固件升级文件校验错误。",
    "firmware.error.200108": "固件升级文件不存在。",
    "firmware.error.200109": "参数错误。",
    "firmware.error.200110": "没有权限删除升级包文件。",
    "firmware.error.200111": "升级包文件删除失败。",
    "firmware.error.200112": "升级包解压失败。",
    "firmware.error.200113": "数据库操作失败。",
    "firmware.error.200114": "没有可用设备需要升级。",
    "firmware.error.200115": "生效策略不合法。",
    "firmware.error.200116": "时间格式不正确。",
    "firmware.error.200117": "任务创建失败。",
    "firmware.error.200119": "操作失败。",
    "firmware.error.200120": "操作部分成功。",
    "firmware.error.200121": "操作失败，任务不存在。",
    "firmware.error.200122": "操作失败，任务状态错误。只有挂起或失败的任务才支持恢复。",
    "firmware.error.200123": "操作失败，该任务处于执行状态。",
    "firmware.error.200124": "操作失败，该任务处于等待状态。",
    "firmware.error.200125": "操作失败，生效时间错误。",
    "firmware.error.200128": "数据库操作错误。",
    "firmware.error.200130": "操作对象不存在。",
    "firmware.error.200131": "操作失败，该任务处于挂起状态。",
    "firmware.error.200132": "设备加锁失败，可能原因：设备正在被其他eSight业务使用，请稍后重试。",
    "firmware.error.200133": "无法获取交换板版本信息，可能原因为当前交换板版本过低不支持升级或交换板无法连通，请刷新交换板所在服务器后重试。",
    "firmware.error.200134": "操作失败，任务状态错误，该任务已结束。",
    "firmware.error.200135": "操作失败，升级包已不存在，请重新创建任务。",
    "firmware.error.200137": "升级包正在下载，删除失败。",
    "firmware.error.200140": "对刀片服务器MM板加锁失败，可能原因为其他部件在做固件升级。",
    "firmware.error.300101": "eSight剩余空间不足，请清理磁盘空间。",
    "firmware.error.300102": "操作失败，设备繁忙。",
    "firmware.error.300103": "升级包文件大小超过最大200M限制。",
    "firmware.error.300104": "文件类型不正确。",
    "firmware.error.300105": "删除升级包失败，系统内部异常。",
    "firmware.error.300106": "升级任务名称重复。",
    "firmware.error.300107": "升级包名称重复。",
    "firmware.error.300108": "设备不存在。可能原因：设备被执行过删除操作。",
    "firmware.error.300109": "升级失败，HMM板重启失败。",
    "firmware.error.300110": "升级失败，重启BMC失败。",
    "firmware.error.300111": "升级失败，重启服务器失败。",
    "firmware.error.300112": "升级包文件名不能超过128位。",
    "firmware.error.300113": "升级失败，重启交换板失败。",
    "firmware.error.300201": "存在固件升级自动化任务正在执行，请稍后操作。",
    //#固件升级错误码定义
    "firmware.error.1001": "参数错误。",
    "firmware.error.1002": "虚拟媒体连接失败，可能原因：设备不支持、服务器连接失败、服务器虚拟媒体连接已被占用或机架、高密服务器支持VMM加密时没有采用SNMP V3协议接入。",
    "firmware.error.1003": "设置服务器重启失败。",
    "firmware.error.1004": "加载SimpleOS失败。",
    "firmware.error.1005": "配置工具包下载失败。",
    "firmware.error.1006": "获取设备类型失败。",
    "firmware.error.1007": "未知异常错误。",
    "firmware.error.1008": "文件目录创建失败。",
    "firmware.error.1009": "配置文件（XML）生成失败。",
    "firmware.error.1010": "Sftp参数获取失败。",
    "firmware.error.1011": "配置工具包执行升级失败。",
    "firmware.error.2001": "下载升级文件失败。",
    "firmware.error.2002": "升级失败，可能原因：设备或者机框繁忙，存在其他正在执行的升级任务。",
    "firmware.error.1100": "上传升级文件失败，可能原因：网络异常、管理用户认证失败或设备缓存容量不足。",
    "firmware.error.3001": "上传升级文件失败，请修改SNMP协议模板，采用V3协议进行通信。",
    "firmware.error.1200": "升级失败。",
    "firmware.error.1201": "升级命令下发失败，可能原因：网络异常。",
    "firmware.error.1202": "升级失败，设备侧启动升级失败。",
    "firmware.error.1203": "升级失败，设备当前版本和要升级的版本相同。",
    "firmware.error.1204": "升级失败，升级文件不存在。",
    "firmware.error.1205": "升级失败，升级文件不正确。",
    "firmware.error.1206": "升级失败，升级设备内存不足。",
    "firmware.error.1207": "升级失败，正在同步备区或正在进行主备一致性检查。",
    "firmware.error.1208": "升级失败，业务系统上电中，不支持升级。",
    "firmware.error.1209": "升级失败，文件下载失败。",
    "firmware.error.1210": "升级失败，升级程序正在运行中。",
    "firmware.error.1211": "升级失败，设备当前在上电状态，不支持BIOS升级。",
    "firmware.error.1212": "升级失败，升级文件名冲突。交换板Fabric平面升级相同名称升级文件仅可使用一次。",
    "firmware.error.1213": "升级失败，升级响应超时。",
    "firmware.error.1214": "升级失败，升级目录空间不足。",
    "firmware.error.1218": "升级失败，升级进度无法获取。",
    "firmware.error.-1": "升级失败，可能原因：网络异常或升级过程中eSight重启。",
    "firmware.error.0": "升级成功。",
    "firmware.error.300301": "没有可用升级包。",
    "firmware.error.300302": "设备处于堆叠备板或者堆叠从板状态。",
    "firmware.error.300303": "没有对应驱动包或硬件无响应。",
    "firmware.error.300304": "设备通信失败，可能原因：网络异常，SNMP用户名密码错误，SNMP使用的不是V3协议。",
    "firmware.error.300401": "驱动升级错误，BMC或BMA没有响应。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.300402": "驱动升级错误，上传驱动文件失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.300403": "驱动升级错误，脚本执行过程中失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.300404": "驱动升级错误，升级文件错误。",

    "firmware.error.300501": "大包升级错误，调用工具更新大包失败。",
    "firmware.error.300502": "大包升级错误，下载工具未返回进度。",
    "firmware.error.300503": "大包升级错误，拷贝文件失败。",
    //创建升级任务错误码
    "firmware.error.20010901": "任务名称不合法。",
    "firmware.error.20010902": "任务描述不合法。",
    "firmware.error.20010903": "任务升级时间策略或者时间格式错误。",
    "firmware.error.20010904": "所选的固件参数错误。",
    "firmware.error.20010905": "生效方式参数错误。",
    "firmware.error.20010906": "升级策略参数错误。",
    "firmware.error.20010907": "基线包错误。",
    "firmware.error.20010908": "升级设备参数错误。",
    "firmware.error.20010909": "升级设备超出限制数量。",
    "firmware.error.20010910": "非关联基线包中，同一个设备升级的固件包或驱动包类型不能重复。",
    "firmware.error.20010911": "存在部分设备没有可用的升级项。可能原因：</br>1.所选升级固件包不支持所选设备。</br>2.所选升级固件没有可用升级包。",
    //###########基线包管理##############
    "firmware.error.200150": "用户没有权限。",
    "firmware.error.200000": "基线包上传成功。",
    "firmware.error.200001": "基线包上传失败，参数不合法。",
    "firmware.error.200002": "基线包上传失败，已存在相同名称的基线包。",
    "firmware.error.200003": "基线包上传失败，上传文件大小超出5G。",
    "firmware.error.200004": "基线包上传失败，创建父目录失败。",
    "firmware.error.200005": "基线包上传失败，保存文件错误。",
    "firmware.error.200006": "基线包上传失败，文件大小校验错误。",
    "firmware.error.200007": "基线包上传失败，文件内容上传不全。",
    "firmware.error.200008": "基线包上传失败，eSight剩余空间不足5G。",
    "firmware.error.200009": "基线包上传失败，上传的文件类型不合法。",
    "firmware.error.200010": "基线包取消上传失败。",
    "firmware.error.200100": "基线包上传失败，升级包描述文件不存在。",
    "firmware.error.200112": "基线包上传失败，升级包解压失败。",
    "firmware.error.200999": "未知错误。",
    "firmware.error.300200": "基线包上传失败，XML文件格式不正确。",
    "firmware.error.300504": "创建目录失败。",
    "firmware.error.200141": "存在设备已经关联基线包或设备不存在。",
    "firmware.error.300505": "下载条件为空，请至少添加一条。",
    "firmware.error.300506": "基线包下载失败，调用工具下载大包失败。",
    "firmware.error.300507": "基线包下载失败，查询进度失败。",
    "firmware.error.300508": "基线包下载失败，拷贝文件失败。",
    "firmware.error.53101": "基线包上传还未结束。",
    "firmware.error.500005": "升级包上传任务创建成功。",
    "firmware.error.500006": "升级包上传任务名为空。",
    "firmware.error.500007": "设备不存在或设备类型错误。",
    "firmware.error.-2": "其它异常，CMC或iBMC重启没有完成。",
    "firmware.error.-3": "版本相同，升级失败。",
    "firmware.error.-4": "升级文件不存在，升级失败。",
    "firmware.error.-5": "升级文件错误，CMC或iBMC重启没有完成。",
    "firmware.error.-6": "KunLun服务器内存不足。",
    "firmware.error.-7": "正在进行主备一致性检测。CMC重启没有完成。",
    "firmware.error.-8": "业务系统上电时，不支持升级。",
    "firmware.error.-9": "不支持升级。",
    "firmware.error.-11": "文件传输失败，iBMC或CMC重启没有完成。",
    "firmware.error.-12": "升级程序正在运行中。",
    "firmware.error.-13": "升级包文件名称冲突。",
    "firmware.error.-14": "响应超时。",
    "firmware.error.-15": "升级目录空间不足。",
    "firmware.error.-17": "LCD固件不在位。",
    "firmware.error.-19": "主备CMC都在位时，主CMC升级失败。",
    "firmware.error.-20": "业务系统上电时，不支持升级。",
    "firmware.error.4001": "升级命令参数错误。",
    "firmware.error.4002": "发送升级命令失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.4003": "打开SSH开关失败或查询SSH状态失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.4004": "设备下电失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.4005": "设备重启失败或设备不在位。",
    "firmware.error.4006": "查询进度失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.4007": "查询进度超时。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.4008": "查询失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.4009": "启动升级失败。可能原因：协议参数输入错误，设备异常重启，网络中断。",
    "firmware.error.-10": "KunLun设备报错，不支持升级。",
    "firmware.error.-16": "KunLun设备报错，不支持升级。",
    "firmware.error.-18": "KunLun设备报错，不支持升级。",

    //------------------固件升级-------------

    //------------------模板管理-------------
    "deploy.error.-1": "参数错误。",

    "deploy.error.201": "操作对象不存在。",

    "deploy.error.51522": "软件包上传失败，请检查文件类型和大小。",
    "deploy.error.51524": "剩余空间不足，软件包大小超出部署系统的剩余空间或文件大小超过10G。",
    "deploy.error.51518": "输入的文件名称格式不合法。",
    "deploy.error.51519": "上传的文件类型不合法。",

    "deploy.error.51001": "参数不合法。",
    "deploy.error.51101": "创建模板失败。",
    "deploy.error.51110": "创建模板失败，软件名称或启动文件不存在。启动文件完整路径必须是携带后缀名的全文件名。",
    "deploy.error.51201": "创建相似模板失败。",
    "deploy.error.51301": "修改模板失败。",
    "deploy.error.51302": "修改模板失败，软件名称或启动文件不存在。启动文件完整路径必须是携带后缀名的全文件名。",
    "deploy.error.51303": "修改模板失败，密码必须为8~32个字符，且至少包含大写字母、小写字母、数字和特殊字符（`~!@#$%^&*()-_\":\"+\|[{}];:'\"\",<.>/?）中的两种。",
    "deploy.error.51304": "操作失败，交换板命令中不能包含？、******和中文，请修改后重新操作。",
    "deploy.error.51401": "删除模板失败。",
    "deploy.error.51403": "删除模板失败，对象已不存在。",
    "deploy.error.51404": "删除模板失败，数据库操作失败或未知错误。",
    "deploy.error.51405": "所选择的软件源不存在。",

    "deploy.error.51501": "导入模板失败。",
    "deploy.error.51601": "导出模板失败。",
    "deploy.error.51701": "刷新模板列表失败。",
    "deploy.error.51801": "查询模板失败。",
    "deploy.error.51901": "获取模板详情失败。",
    "deploy.error.51991": "部署模板失败。",
    "deploy.error.51992": "部署模板失败，软件路径或启动文件不存在。",
    "deploy.error.51993": "部署模板失败，软件路径或密码不存在，请修改模板后重新部署。",
    "deploy.error.52001": "获取设备列表失败。",
    "deploy.error.52101": "部署模板失败。",
    "deploy.error.53101": "文件上传还未结束,添加软件源失败。",
    "deploy.error.53201": "删除软件源失败。",
    "deploy.error.53202": "删除软件源部分成功。",
    "deploy.error.53301": "刷新软件源失败。",
    "deploy.error.53401": "查询软件源失败。",
    "deploy.error.53410": "添加软件源失败，软件源名称已经存在。",
    "deploy.error.53412": "安装文件不存在。",
    "deploy.error.53501": "获取软件源详情失败。",
    "deploy.error.53601": "修改软件源失败。",
    "deploy.error.53602": "修改软件源失败，软件源正在使用中。",

    "deploy.error.54001": "操作对象不存在。",
    "deploy.error.59002": "操作对象不存在或已被删除。",
    "deploy.error.59003": "数据库操作失败或未知错误。",
    "deploy.error.59004": "不能删除正在运行的任务。",

    "deploy.error.51102": "该名称的模板已存在。",
    "deploy.error.54011": "删除任务失败。",
    "deploy.error.54012": "删除任务部分成功。",
    "deploy.error.54013": "删除任务失败，对象已不存在。",
    "deploy.error.54014": "删除任务失败，数据库操作失败或未知错误。",
    "deploy.error.54020": "修改任务失败，任务正在运行。",

    "deploy.error.56011": "挂起任务失败。",
    "deploy.error.56012": "挂起任务部分成功。",
    "deploy.error.56013": "挂起任务失败，对象已不存在。",

    "deploy.error.56019": "恢复任务失败。",
    "deploy.error.56020": "恢复任务部分成功。",
    "deploy.error.56021": "修改任务失败。",

    "deploy.error.102418": "请求超时。",
    "deploy.error.148403": "设备正在进行其它部署操作。",
    "deploy.error.148409": "获取设备单板序列号失败。",
    "deploy.error.148412": "该设备不支持NTP配置。",
    "deploy.error.148451": "设备正在进行其它部署操作。",
    "deploy.error.148452": "配置异常。",
    "deploy.error.148453": "配置命令下发失败。",
    "deploy.error.148454": "执行SNMP命令失败。",
    "deploy.error.148455": "DHCP可分配的IP地址不足。",
    "deploy.error.148459": "部署OS超时。",
    "deploy.error.148499": "任务被中断。",
    "deploy.error.148901": "添加任务失败。",
    "deploy.error.148902": "停止任务失败。",
    "deploy.error.148903": "删除任务失败。",
    "deploy.error.148904": "修改任务失败。",
    "deploy.error.148905": "恢复任务失败。",
    "deploy.error.148906": "修改任务失败。",
    "deploy.error.149001": "模板参数不合法。",
    "deploy.error.149002": "模板格式不正确。",
    "deploy.error.149003": "模板已存在。",
    "deploy.error.149004": "文件解析失败，请检查导入的文件。",
    "deploy.error.149100": "启动项配置失败。",
    "deploy.error.149101": "NTP配置失败。",
    "deploy.error.149102": "DNS配置失败。",
    "deploy.error.149103": "LDAP配置失败。",
    "deploy.error.149104": "功率封顶配置失败。可能原因：</br>1.设备不支持功率封顶；</br>2.功率封顶值设置不合理。",
    "deploy.error.150110": "重启服务器失败。",
    "deploy.error.150111": "获取MAC地址信息失败。",

    "deploy.error.150112": "获取网卡信息失败。",
    "deploy.error.150113": "创建配置文件失败。",
    "deploy.error.150115": "线程等待失败。",
    "deploy.error.150116": "软件源不存在。",
    "deploy.error.150117": "创建静默安装文件失败。",
    "deploy.error.150118": "部署失败。",
    "deploy.error.150119": "配置RAID失败。",
    "deploy.error.150120": "在服务器上运行WINPE出错。",
    "deploy.error.150121": "拷贝文件失败。",
    "deploy.error.150122": "OS部署完成，配置网卡等组件失败。",
    "deploy.error.150123": "由于系统性能及其他原因导致当任务部署时，已经过期。",
    "deploy.error.150124": "任务已过期，无法执行。",
    "deploy.error.150125": "由于系统性能或其他原因导致部署任务时，任务首次执行时间已过。在下个任务周期，系统将自动执行该任务。",
    "deploy.error.150150": "OS模板信息错误。",
    "deploy.error.150151": "部署服务异常。",
    "deploy.error.150152": "解析任务计划时间出错。",
    "deploy.error.150153": "FTP未开启。",
    "deploy.error.150154": "TFTP未开启。",
    "deploy.error.150155": "DHCP未开启。",
    "deploy.error.150156": "数据类型转换失败。",
    "deploy.error.150157": "连接设备失败。可能原因：网络异常、管理协议参数修改或者其他原因导致设备暂时无法管理。",
    "deploy.error.150158": "内核文件或根文件系统或引导程序不存在。可能原因：配置部署扩展包未安装。",
    "deploy.error.150159": "设置PXE启动失败。",
    "deploy.error.150160": "文件共享服务不可用。",
    "deploy.error.150161": "内核文件或根文件系统或引导程序不存在。可能原因：配置部署扩展包未安装。",
    "deploy.error.150170": "DHCP无可分配的IP地址，请修改DHCP地址的可分配网段。",
    "deploy.error.148456": "下电失败。",
    "deploy.error.148457": "上电失败。",
    "deploy.error.148405": "BIOS从PXE启动失败。",
    "deploy.error.150132": "OS部署硬盘检测失败。",
    "deploy.error.150133": "OS部署硬盘检测失败。",
    "deploy.error.150134": "模板硬盘数量大于服务器硬盘数量。",
    "deploy.error.150135": "模板硬盘容量大于服务器硬盘容量。",
    "deploy.error.148500": "任务名称重复。",
    "deploy.error.148501": "设备在无状态设备组中，且为下电状态，不能进行带内和OS部署，请参考联机帮助解决。",
    "deploy.error.11": "不支持的RAID卡型号。",
    "deploy.error.12": "创建RAID失败。",
    "deploy.error.13": "没有足够的硬盘配置RAID。",
    "deploy.error.14": "RAID卡不支持该RAID级别。",
    "deploy.error.15": "创建RAID失败。",
    "deploy.error.16": "创建RAID失败。",
    "deploy.error.18": "已有RAID配置，请先删除后重新配置。",
    "deploy.error.17": "创建RAID失败。",
    "deploy.error.148458": "读取RAID部署结果超时。可能原因：与设备业务通信异常，请检查网络配置",
    "deploy.error.148401": "eSight意外终止。",
    "deploy.error.148402": "需要部署的设备不存在。可能原因：设备被执行过删除操作。",
    "deploy.error.149200": " 操作失败，用户无权限。",
    "deploy.error.148410": "该设备在无状态设备列表中，请将该设备从无状态设备列表中移除后重新部署。",
    "deploy.error.148411": "该设备类型不支持iBMC配置部署。",

    "deploy.error.148801": "虚拟媒体连接失败，可能原因：</br>1.服务器连接失败；</br>2.服务器虚拟媒体连接已被占用；</br>3.机架、高密服务器支持VMM加密时没有采用SNMP V3协议接入；</br>4.固件版本太低，不支持该功能。",
    "deploy.error.148802": "设置服务器重启失败。可能原因：与设备通信异常，请检查网络配置。",
    "deploy.error.148803": "加载SimpleOS失败。可能原因：</br>1.与设备业务通信异常；</br>2.部署过程中设备被进行了其它操作。",
    "deploy.error.148804": "下载配置工具包失败。可能原因：eSight侧SFTP服务未启动。",
    "deploy.error.148805": "配置BIOS失败。",
    "deploy.error.148806": "RAID卡配置失败。可能原因：</br>1.RAID卡型号不匹配；</br>2.硬盘槽位不匹配；</br>3.磁盘已有RAID，部署时没有删除原RAID。",
    "deploy.error.148807": "配置HBA失败。可能原因：HBA卡型号或槽位不匹配。",
    "deploy.error.148808": "配置CNA失败。可能原因：CNA卡型号或槽位不匹配。如果CNA为MZ512型号，则无法插在CH220 V3刀片的1、4号槽位。",
    "deploy.error.148810": "simpleOS不存在。",
    "deploy.error.148811": "创建CNA配置文件失败。",
    "deploy.error.148812": "配置CNA失败。解析配置结果失败。",

    "deploy.error.148815": "创建配置文件失败。",
    "deploy.error.148816": "查询SFTP参数失败。",
    "deploy.error.148817": "解析配置结果文件失败。",
    "deploy.error.148818": "解析配置结果文件失败。",
    "deploy.error.148820": "HBA配置超时。",
    "deploy.error.148821": "下载配置文件失败。",
    "deploy.error.11000000": "eSightCfg工具包的未知错误。",

    "deploy.error.10004001": "RAID卡配置失败。可能原因：错误的参数或配置失败。",
    "deploy.error.10004003": "物理盘不符合RAID组要求。",
    "deploy.error.10040011": "已配置的物理盘和未配置的物理盘不能一起配置RAID。",
    "deploy.error.10040012": "有一个物理盘不存在。",
    "deploy.error.10040013": "物理盘容量不符合配置要求。",
    "deploy.error.10040030": "配置失败。",
    "deploy.error.10400256": "清空已存在的配置失败。",
    "deploy.error.10400257": "设置启动盘时所设置的逻辑盘不存在。",
    "deploy.error.10400258": "配置结果校验失败。",
    "deploy.error.10400259": "RAID控制器类型不匹配。",
    "deploy.error.10003001": "错误的参数或配置失败。",
    "deploy.error.10030064": "错误的模式或适配器不支持该模式设置。",
    "deploy.error.10030091": "设置的WWPN或WWNN已经存在。",
    "deploy.error.10300251": "硬件或驱动版本不支持。",
    "deploy.error.10300255": "WWN或MAC地址格式不合法。",
    "deploy.error.10300300": "没有找到CNA卡或者卡类型不正确。",
    "deploy.error.10300301": "没有找到HBA卡或者卡类型不正确。",
    "deploy.error.10300302": "配置CNA卡带宽错误。",
    "deploy.error.10300303": "CNA卡只允许PF2为FCoE或iSCSI模式。",
    "deploy.error.10300304": "CNA卡一个端口需要有4个PF节点。",
    "deploy.error.10300310": "CNA卡配置错误。可能原因：CNA卡安装槽位错误、CPU或内存等硬件部件配置错误或CNA卡的固件版本不兼容。",
    "deploy.error.10300320": "HBA卡配置错误。",
    "deploy.error.10300400": "CNA卡下的单个Port所属PF最小带宽之和不等于100。",
    "deploy.error.10300401": "CNA卡的PF vlan不在 2到4094之间。",



    "deploy.error.150100": "数据库操作失败。",
    "deploy.error.150101": "参数不合法。",
    "deploy.error.150102": "操作对象不存在或已被删除。",
    "deploy.error.150103": "软件源正在使用中。",
    "deploy.error.150104": "删除文件失败。",


    "deploy.error.148920": "停止任务失败。",
    "deploy.error.148921": "停止任务部分成功。",
    "deploy.error.148910": "任务状态错误。",
    "deploy.error.601": "任务正在运行，挂起失败。",

    "deploy.error.53701": "软件源上传失败。",
    "deploy.error.53702": "目标文件不存在。",
    "deploy.error.53703": "软件源参数校验失败。",
    "deploy.error.53704": "添加软件源失败，可能原因为数据库操作失败",
    "deploy.error.56008": "任务当前为非挂起状态，只有挂起的任务才能恢复。",
    "deploy.error.56009": "任务当前为非空闲状态，只有空闲的任务才能挂起。",


    "deploy.error.145001": "要部署软件不存在。",
    "deploy.error.145002": "获取设备IP失败，请检查服务器管理协议配置是否正确。",
    "deploy.error.145003": "调用插件失败。",
    "deploy.error.460": "配置结果未生成。",
    "deploy.error.2003": "安装软件失败。可能原因：安装脚本执行失败。",
    "deploy.error.145004": "配置超时。可能原因：软件安装失败或模板安装时间过短导致软件未安装完成。",
    "deploy.error.145005": "查询管理协议失败，请检查服务器管理协议配置是否正确。",
    "deploy.error.145006": "HostAgent中插件不存在。",
    "deploy.error.145007": "插件调用失败。",
    "deploy.error.145008": "配置软件分发失败。",
    "deploy.error.145009": "软件安装时间不够。",
    "deploy.error.13087": "SFTP服务器无法连接。",
    "deploy.error.13088": "Agent安装SFTP客户端工具失败。",
    "deploy.error.13089": "Agent安装SFTP客户端工具失败。",
    "deploy.error.13090": "连接SFTP服务器失败。可能原因：网管侧SFTP服务未启动。",
    "deploy.error.13091": "Agent安装SFTP客户端工具失败。",
    "deploy.error.13092": "创建目录失败。可能原因：HostAgent代理无文件操作权限。",
    "deploy.error.13097": " 下载文件失败。可能原因：</br>1.eSight侧SFTP服务未启动；</br>2.与设备业务通信异常，请检查网络配置。",
    "deploy.error.13108": "安装应用软件失败。",
    "deploy.error.13112": "安装应用软件失败。",
    "deploy.error.13109": "要部署软件不存在。",
    "deploy.error.13113": "剩余空间不足，软件包大小超出部署系统的剩余空间。",
    "deploy.error.13114": "设备上已经存在待部署的软件，请到设备上software_deploy目录下查看。",




    "deploy.error.150200": "虚拟媒体连接失败。可能原因：</br>1.服务器连接失败；</br>2.服务器虚拟媒体连接已被占用；</br>3.机架、高密服务器支持VMM加密时没有采用SNMP V3协议接入；</br>4.固件版本太低，不支持该功能。",
    "deploy.error.150201": "虚拟媒体连接失败。可能原因：</br>1.服务器连接失败；</br>2.服务器虚拟媒体连接已被占用；</br>3.机架、高密服务器支持VMM加密时没有采用SNMP V3协议接入；</br>4.固件版本太低，不支持该功能。",
    "deploy.error.150202": "虚拟媒体连接失败。可能原因：</br>1.服务器连接失败；</br>2.服务器虚拟媒体连接已被占用；</br>3.机架、高密服务器支持VMM加密时没有采用SNMP V3协议接入；</br>4.固件版本太低，不支持该功能。",
    "deploy.error.150105": "软件源未就绪。请等待软件源制作完成。",
    "deploy.error.160000": "文件大小最大为10MB。",
    "deploy.error.160001": "文件格式只能为xml或者cfg文件。",
    "deploy.error.160002": "参数错误。",
    "deploy.error.150431": "配置命令执行失败。",
    "deploy.error.150430": "设备连接失败，可能原因：用户名密码错误或连接超时。",


    "deploy.error.0": "部署成功。",
    "deploy.error.150500": "设备连接失败，可能原因：设备不存在。",
    "deploy.error.150501": "设备连接失败，可能原因：设备离线。",
    "deploy.error.150502": "设备连接失败，可能原因：设备繁忙。",
    "deploy.error.150503": "设备连接失败，可能原因：用户名密码错误或者连接超时。",
    "deploy.error.150504": "命令执行失败。",
    "deploy.error.150505": "任务失败，该设备没有堆叠。",
    "deploy.error.150506": "任务失败，设备加锁失败。",
    "deploy.error.150510": "任务部署失败。",
    "deploy.error.150511": "命令下发无响应。",
    "deploy.error.150512": "交换板配置超时失败。",


    "deploy.error.150000": "没有可以配对的交换板创建堆叠。",
    "deploy.error.150001": "创建堆叠的两个交换板型号不匹配。",
    "deploy.error.150002": "交换板创建堆叠失败，可能重启失败。",
    "deploy.error.150003": "交换板FC平面通信失败。可能原因：</br>1.服务器交换板协议参数管理页面FC平面参数配置不正确；</br>2.与交换板FC平面通信异常。",
    "deploy.error.150004": "配置堆叠域失败。可能原因：部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.150005": "交换板重启失败。可能原因：部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.150006": "创建堆叠命令下发失败。",
    "deploy.error.150007": "物理端口加入堆叠口命令下发失败，可能原因：端口做了其它业务配置。",
    "deploy.error.150008": "查看堆叠失败。可能原因：部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.150009": "保存当前配置失败。可能原因：部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.150010": "Fabric平面FCOE配置失败。可能原因：部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.149202": "所选设备不可以创建堆叠。",
    "deploy.error.150011": "FC平面FCOE配置失败。可能原因：部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.150012": "VLAN和自定义配置下发超时。可能原因：</br>1.与交换板通信异常； </br>2.部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.150013": "交换板创建堆叠失败。可能原因：</br>1.模板中配置的物理端口间没有直连；</br>2.部署过程中交换板被进行了其它配置或操作。",
    "deploy.error.150016": "创建堆叠失败，对于CX111和CX915型号的交换板，在创建模板时需要选择加入堆叠的物理端口。",


    "deploy.error.150300": "ServiceCD不存在或其文件名不正确。",
    "deploy.error.150301": "挂载ServiceCD失败。可能原因：</br>1.服务器连接失败；</br>2.服务器虚拟媒体连接已被占用；</br>3.机架、高密服务器支持VMM加密时没有采用SNMP V3协议接入；</br>4.固件版本太低，不支持该功能。",
    "deploy.error.150302": "加载ServiceCD超时。可能原因：网络异常导致服务器连接失败。",
    "deploy.error.150303": "断开ServiceCD失败。可能原因：网络异常导致服务器连接失败。",
    "deploy.error.150304": "挂载OS失败。可能原因：</br>1.服务器连接失败；</br>2.服务器虚拟媒体连接已被占用；</br>3.机架、高密服务器支持VMM加密时没有采用SNMP V3协议接入；</br>4.固件版本太低，不支持该功能。",
    "deploy.error.150305": "设置启动安装OS失败。可能原因：网络异常导致服务器连接失败。",
    "deploy.error.150306": "查询OS安装进度失败。可能原因：网络异常导致服务器连接失败。",
    "deploy.error.150307": "安装OS超时。可能原因：网络异常导致服务器连接失败。",
    "deploy.error.150308": "断开软件源失败。可能原因：网络异常导致服务器连接失败。",
    "deploy.error.150309": "部署OS失败。",
    "deploy.error.150310": "部署OS失败。配置文件模板不存在。",
    "deploy.error.150311": "部署OS失败。生成安装配置文件失败。",
    "deploy.error.150312": "下发配置信息失败，可能原因：设备被其他操作中断或网络异常。",

    "deploy.error.170101": "ServiceCD读取SystemInfo失败。",
    "deploy.error.170102": "ServiceCD读取OS类型失败。",
    "deploy.error.170103": "系统安装参数错误。",
    "deploy.error.170104": "拷贝驱动和配置文件失败。",
    "deploy.error.170105": "ServiceCD无法读取OS配置参数。",
    "deploy.error.170106": "OS配置参数为空。",
    "deploy.error.170107": "ServiceCD保存配置信息失败。",
    "deploy.error.170108": "ServiceCD找不到操作系统光盘。",
    "deploy.error.170109": "从光驱读取配置文件失败。",
    "deploy.error.170110": "获取设备sn失败。",
    "deploy.error.170111": "读取硬盘信息失败，可能原因：无可用硬盘。",
    "deploy.error.170112": "ServiceCD无法读取OS配置参数。",
    "deploy.error.170113": "检测系统光盘失败。",
    "deploy.error.170114": "设置设备重启顺序失败。",
    "deploy.error.170115": "模板中设置的分区空间大小大于设备实际的空间大小。",

    "deploy.error.180100": "修改密码失败：SFTP服务不存在。",
    "deploy.error.180101": "修改密码失败：获取SFTP用户失败。",
    "deploy.error.180102": "修改密码失败：获取SFTP信息失败。",
    "deploy.error.180103": "用户名或者密码错误。",
    "deploy.error.180104": "密码不符合要求。",
    "deploy.error.180105": "新密码不能与旧密码相同。",
    "deploy.error.180106": "确认密码与密码不相同。",
    "deploy.error.180107": "输入密码错误次数超过5次，请等待15分钟后再试。",
    "deploy.error.180108": "更新SFTP服务用户信息失败。",
    "deploy.error.180109": "SFTP用户已存在。",
    "deploy.error.180110": "修改上传密码成功。",
    "deploy.error.57000": "导入静默文件成功。",
    "deploy.error.150313": "导入的静默文件不存在。",
    "deploy.error.150314": "挂载静默文件夹失败。",
    "deploy.error.150315": "serviceCD获取静默文件失败。",
    "deploy.error.150316": "静默文件内容非法，请参看联机帮助中生成方法。"

    //------------------模板管理-------------

}

var errorCode_en = {
        //-------------------自定义---------------------------------------------
        "0": "Successful",
        "1204": "eSight connection failed. please try again.",
        "-331": "eSight connection failed. please try again.",
        "201": "query or delete failed, the object to be operated does not exist",
        "149201": "License number is insufficient.",
        "-99999": "OperationFailed: unknownerror",
        "-90001": "System internal error, please initialize",
        "-90002": "Please configure eSight first",
        "-90003": "Login status effectiveness, Please login vCenter again",
        "-90004": "Now there are no failed tasks that can be cleared",
        "-90005": "The user name of eSight does not match the password or the account does not exist.",
        "-80009": "Failed to connect current eSight:A error occurred when connecting to the eSight server.",
        "-80010": "Failed to connect current eSight:An error occurred when connecting to the eSight server. No connection could be made because the target machine actively refused.",
        "-80011": "Sytem can not find this eSight",
        "-81001": "Failed to connect current eSight:An error occurred when connecting to the eSight server. Network connection error.",
        "-70001": "No data found in the database.",
        //http
        "-50400": "Failed to connect current eSight:BadRequest indicates that the request could not be understood by the server. BadRequest is sent when no other error is applicable, or if the exact error is unknown or does not have its own error code.",
        "-50401": "Failed to connect current eSight:Unauthorized indicates that the requested resource requires authentication. The WWW-Authenticate header contains the details of how to perform the authentication.",
        "-50402": "Failed to connect current eSight:PaymentRequired is reserved for future use.",
        "-50403": "Failed to connect current eSight:Forbidden indicates that the server refuses to fulfill the request.",
        "-50404": "Failed to connect current eSight:NotFound indicates that the requested resource does not exist on the server.",
        "-50405": "Failed to connect current eSight:MethodNotAllowed indicates that the request method (POST or GET) is not allowed on the requested resource.",
        "-50406": "Failed to connect current eSight:NotAcceptable indicates that the client has indicated with Accept headers that it will not accept any of the available representations of the resource.",
        "-50407": "Failed to connect current eSight:ProxyAuthenticationRequired indicates that the requested proxy requires authentication. The Proxy-authenticate header contains the details of how to perform the authentication.",
        "-50408": "Failed to connect current eSight:RequestTimeout indicates that the client did not send a request within the time the server was expecting the request.",
        "-50409": "Failed to connect current eSight:Conflict indicates that the request could not be carried out because of a conflict on the server.",
        "-50410": "Failed to connect current eSight:Gone indicates that the requested resource is no longer available.",
        "-50411": "Failed to connect current eSight:LengthRequired indicates that the required Content-length header is missing.",
        "-50412": "Failed to connect current eSight:PreconditionFailed indicates that a condition set for this request failed, and the request cannot be carried out. Conditions are set with conditional request headers like If-Match, If-None-Match, or If-Unmodified-Since.",
        "-50413": "Failed to connect current eSight:RequestEntityTooLarge indicates that the request is too large for the server to process.",
        "-50414": "Failed to connect current eSight:RequestUriTooLong indicates that the URI is too long.",
        "-50415": "Failed to connect current eSight:UnsupportedMediaType indicates that the request is an unsupported type.",
        "-50416": "Failed to connect current eSight:RequestedRangeNotSatisfiable indicates that the range of data requested from the resource cannot be returned, either because the beginning of the range is before the beginning of the resource, or the end of the range is after the end of the resource.",
        "-50417": "Failed to connect current eSight:ExpectationFailed indicates that an expectation given in an Expect header could not be met by the server.",
        "-50500": "Failed to connect current eSight:InternalServerError indicates that a generic error has occurred on the server.",
        "-50501": "Failed to connect current eSight:NotImplemented indicates that the server does not support the requested function.",
        "-50502": "Failed to connect current eSight:BadGateway indicates that an intermediate proxy server received a bad response from another proxy or the origin server.",
        "-50503": "Failed to connect current eSight:ServiceUnavailable indicates that the server is temporarily unavailable, usually due to high load or maintenance.",
        "-50504": "Failed to connect current eSight:GatewayTimeout indicates that an intermediate proxy server timed out while waiting for a response from another proxy or the origin server.",
        "-50505": "Failed to connect current eSight:HttpVersionNotSupported indicates that the requested HTTP version is not supported by the server.",
        "firmware.error.51001": "Invalid parameter value.",
		"10000": "eSight returns an internal error.",
		"firmware.error.10000": "eSight returns an internal error.",
		"deploy.error.10000": "eSight returns an internal error.",
		"firmware.error.99998": "eSight returns. Upload SoftWare is not existed, upload file failed.",
	    "deploy.error.99998": "eSight returns. Upload Software is not existed, upload file failed.",
		"firmware.error.500223": "eSight returns, The description of the firmware type does not match the actual firmware type.",
		"firmware.error.400100": "eSight returns, The firmware upgrade file does not exist.",
		"firmware.error.300509": "eSight returns, The operation failed and the query list failed",
		"deploy.error.200008": "eSight returns, Failed to upload the software: The remaining space in eSight is less than 5 GB.",
		"deploy.error.1100": "eSight returns,Failed to upload the software. Possible cause: A network exception occurred, management user authentication failed, or the cache capacity is insufficient.",
		"deploy.error.52105": "eSight returns, task is running.",
		"deploy.error.52104": "eSight returns, Deleting task failed, system error.",	
		"device.error.-1": "Failed to query server details due to a parameter error.",
        //-------------------自定义---------------------------------------------
        //------------------模板管理-----------------------
        "deploy.error.-1": "Parameter error.",

        "deploy.error.201": "Nonexistent object.",
        "deploy.error.51518": "Invalid file name format.",
        "deploy.error.51519": "Invalid uploaded filetype.",
        "deploy.error.51001": "Invalid parameter value.",

        "deploy.error.51522": "Upload failed. Please check the type and the size of the file.",
        "deploy.error.51524": "The size of the file is larger than 10G or the space required for installing the software package exceeded the free space of the system.",
        "deploy.error.51101": "Failed to create the template.",
        "deploy.error.51110": "Failed to create the template because the software name or the boot file does not exist. The boot file full path must contain suffix.",
        "deploy.error.51201": "Failed to create the similar template.",
        "deploy.error.51301": "Failed to modify the template.",
        "deploy.error.51302": "Failed to modify the template because the software name or the boot file does not exist. The boot file full path must contain suffix.",
        "deploy.error.51303": "Failed to modify the template. The password must contain 8 to 32 characters, including at least any two types of the following: uppercase letters, lowercase letters, digits, and special characters including `~!@#$%^&*()-_\":\"+\|[{}];:'\"\",<.>/?",
        "deploy.error.51304": "Operation failed. A switchboard command cannot contain question masks (?), six asterisks (******), or Chinese characters. Change the command and try again.",
        "deploy.error.51401": "Failed to delete the template.",
        "deploy.error.51402": "Partially succeeded in deleting the template.",
        "deploy.error.51403": "Failed to delete the template. Nonexistent object.",
        "deploy.error.51404": "Failed to delete the template. Database operation failed or unknown error.",
        "deploy.error.51405": "The software selected is not exist.",

        "deploy.error.51501": "Failed to importe the template.",
        "deploy.error.51601": "Failed to exporte the template.",
        "deploy.error.51701": "Failed to refresh the templateList.",
        "deploy.error.51801": "Failed to search the template.",
        "deploy.error.51901": "Failed to get the template detail.",
        "deploy.error.51991": "Failed to deploy the template.",
        "deploy.error.51992": "Failed to deploy the template because the software path or the boot file does not exist.",
        "deploy.error.51993": "Failed to deploy the template because the software path or password does not exist. Modify the template and try again.",
        "deploy.error.52001": "Failed to getting the deployDeviceList.",
        "deploy.error.52101": "Failed to deploy the template.",
        "deploy.error.53101": "Failed to add the software source.",
        "deploy.error.53201": "Failed to delete the software source.",
        "deploy.error.53202": "Partially succeeded in deleting the software source.",

        "deploy.error.53301": "Failed to refresh the software source.",
        "deploy.error.53401": "Failed to search the software source.",
        "deploy.error.53410": "Failed to add the software source. The software source name already exists.",
        "deploy.error.53412": "The installation file does not exist.",
        "deploy.error.53501": "Failed to get the softwaresourceDetail.",
        "deploy.error.53601": "Failed to modify the software source.",
        "deploy.error.53602": "Failed to change the software source. The software source is being used.",

        "deploy.error.54001": "The operation object does not exist.",
        "deploy.error.54011": "Failed to delete the task.",
        "deploy.error.54012": "Partially succeeded in deleting the task.",
        "deploy.error.54013": "Failed to delete the task. Nonexistent object.",
        "deploy.error.54014": "Failed to delete the task. Database operation failed or unknown error.",

        "deploy.error.54020": "Failed to modify the task since it is running.",

        "deploy.error.56011": "Failed to suspend the task.",
        "deploy.error.56012": "Partially succeeded in suspending the task.",
        "deploy.error.56013": "Failed to suspend the task. Nonexistent object.",

        "deploy.error.56019": "Failed to resume the task.",
        "deploy.error.56020": "Partially succeeded in resuming the task.",
        "deploy.error.56021": "Failed to modify the task.",

        "deploy.error.59002": "Nonexistent object.",

        "deploy.error.59003": "Database operation failed or unknown error.",
        "deploy.error.59004": "Can't delete the running task.",

        "deploy.error.51102": "Duplicate template name.",

        "deploy.error.102418": "Request timed out.",
        "deploy.error.148403": "Other deployment operations are being performed on the device.",

        "deploy.error.148409": "Failed to obtain the device board serial number.",

        "deploy.error.148412": "The device does not support the NTP configuration.",

        "deploy.error.148451": "Other deployment operations are being performed on the device.",

        "deploy.error.148452": "Configuration anomaly.",

        "deploy.error.148453": "Failed to send the configuration command.",

        "deploy.error.148454": "Failed to execute the SNMP command.",
        "deploy.error.148455": "DHCP can be allocated IP address is insufficient.",

        "deploy.error.148459": "OS deployment timed out.",

        "deploy.error.148499": "Task interrupted.",

        "deploy.error.148901": "Failed to add the task.",
        "deploy.error.148902": "Failed to stop the task.",
        "deploy.error.148903": "Failed to delete the task.",
        "deploy.error.148904": "Failed to modify the task.",

        "deploy.error.148905": "Failed to recover the task.",

        "deploy.error.148906": "Failed to modify the task.",

        "deploy.error.149001": "Invalid template parameter value.",

        "deploy.error.149002": "Incorrect template format.",
        "deploy.error.149003": "The template already exists.",

        "deploy.error.149004": "Failed to parse the file. Check the imported file.",

        "deploy.error.149100": "Failed to configure the startup items.",

        "deploy.error.149101": "NTP configuration failed.",

        "deploy.error.149102": "DNS configuration failed.",

        "deploy.error.149103": "LDAP configuration failed.",

        "deploy.error.149104": "Power Capping configuration failed. Possible causes: </br>1. The device does not support the Power Capping configuration. </br>2. The power capping value is out of range.",

        "deploy.error.150110": "Failed to restart the server.",
        "deploy.error.150111": "Failed to obtain MAC address information.",

        "deploy.error.150112": "Failed to obtain the network adapter information.",

        "deploy.error.150113": "Failed to create the configuration file.",
        "deploy.error.150115": "Thread waiting failed.",

        "deploy.error.150116": "Nonexistent software source.",

        "deploy.error.150117": "Failed to create the silent installation file.",

        "deploy.error.150118": "Deployment failed.",
        "deploy.error.150119": "RAID configuration failed.",

        "deploy.error.150120": "An error occurred when WINPE is running on the server.",

        "deploy.error.150121": "File copy failed.",

        "deploy.error.150122": "The OS deployment is completed. The deployment of components such as network adapters failed.",

        "deploy.error.150123": "The task has expired upon deployment due to system performance or other causes.",

        "deploy.error.150124": "The task has expired and cannot be executed.",

        "deploy.error.150125": "The first task execution period has expired upon deployment due to system performance or other causes. In the next execution period, the system will automatically execute the task.",

        "deploy.error.150150": "Incorrect OS template.",

        "deploy.error.150151": "Abnormal deployment service.",

        "deploy.error.150152": "An error occurred during the parsing of scheduled task execution time.",

        "deploy.error.150153": "The FTP has not been enabled.",

        "deploy.error.150154": "The TFTP has not been enabled.",

        "deploy.error.150155": "The DHCP has not been enabled.",

        "deploy.error.150156": "Data type conversion failed.",

        "deploy.error.150157": "Failed to connect to the device. Possible cause: The device cannot be properly managed because of a network exception, management protocol parameter change, or other reasons.",
        "deploy.error.150158": "The kernel file, root file system, or boot program does not exist. Possible cause: The configuration deployment extended package is not installed.",

        "deploy.error.150159": "Failed to set the PXE startup.",

        "deploy.error.150160": "Unavailable file sharing service.",

        "deploy.error.150161": "The kernel file, root file system, or boot program does not exist. Possible cause: The configuration deployment extended package is not installed.",

        "deploy.error.150170": "The DHCP server has no assignable IP address. Change the assignable network segment for the DHCP server.",

        "deploy.error.148456": "Power-off failed.",

        "deploy.error.148457": "Power-on failed.",

        "deploy.error.148405": "The BIOS failed to be booted from the PXE.",

        "deploy.error.148500": "Duplicate task name.",

        "deploy.error.148501": "Inband and OS deployment cannot be performed since the device is the stateless device group and powered off. Follow the online help to troubleshoot the fault.",

        "deploy.error.150132": "Disk check for the OS deployment failed.",

        "deploy.error.150133": "Disk check for the OS deployment failed.",

        "deploy.error.150134": "The disk quantity specified in the template is larger than that of servers.",

        "deploy.error.150135": "The disk capacity specified in the template is larger than that of servers.",

        "deploy.error.11": "RAID card model not supported",
        "deploy.error.12": "Failed to create the RAID group.",

        "deploy.error.13": "There is no sufficient disk space to configure RAID groups.",

        "deploy.error.14": "The RAID card does not support the RAID level.",

        "deploy.error.15": "Failed to create the RAID group.",

        "deploy.error.16": "Failed to create the RAID group.",

        "deploy.error.18": "RAID groups already exist. Please delete them and configure RAID groups again.",

        "deploy.error.17": "Failed to create the RAID group.",

        "deploy.error.148458": "Reading the RAID group deployment result timed out. Possible cause: The communication between the device and eSight is abnormal.",

        "deploy.error.148401": "eSight terminated unexpectedly.",

        "deploy.error.148402": "The device to be deployed does not exist. Possible cause: The device has been deleted and added again.",

        "deploy.error.149200": " Operation failed. The user has no permission.",

        "deploy.error.148410 ": "The device is in the stateless device list. Please remove the device from the list and deploy it again.",

        "deploy.error.148411": "The device type does not support the iBMC configuration and deployment.",

        "deploy.error.148801": "Failed to connect to the virtual media. Possible causes: </br>1. The server cannot be connected. </br>2. The link to the server virtual media has been occupied. </br>3. The SNMP v3 protocol is not used by rack servers and high-density servers in VMM encryption. </br>4. The firmware version is too early to support this function.",

        "deploy.error.148802": "Failed to restart the server. Possible cause: The communication between the device and eSight is abnormal. Check the network configurations.",

        "deploy.error.148803": "Failed to load the SimpleOS. Possible cause: </br>1. The communication between the device and eSight is abnormal. </br>2. Other operations are performed on the device during the deployment process.",

        "deploy.error.148804": "Failed to download the configuration tool package. Possible cause: The SFTP service on eSight had not started.",

        "deploy.error.148805": "Failed to configure the BIOS.",

        "deploy.error.148806": "Failed to configure the RAID controller card. Possible cause: </br>1.The RAID controller card model or hard disk slots do not match. </br>2.A RAID array already exists in the disk. The original RAID array is not deleted during deployment.",

        "deploy.error.148807": "Failed to configure the HBA. Possible cause: The HBA model or slot does not match.",
        "deploy.error.148808": "Failed to configure the CNA. Possible cause: The CNA model or slot does not match. If the type of CNA is MZ512,it cannot be inserted in slot 1 or 4 on the CH220 V</br>3.",
        "deploy.error.148810": "The simpleOS is not exsit.",
        "deploy.error.148811": "Failed to create the CNA file.",
        "deploy.error.148812": "Failed to configure the CNA because of a failure to parse the configuration result.",
        "deploy.error.148815": "Failed to create the config file.",
        "deploy.error.148816": "Failed to get the SFTP parameters.",
        "deploy.error.148817": "Failed to resolve the config result file.",
        "deploy.error.148818": "Failed to resolve the config result file.",
        "deploy.error.148820": "HBA configuration timed out.",
        "deploy.error.148821": "Failed to download the config file.",
        "deploy.error.11000000": "Unknow error of eSightCfg package.",

        "deploy.error.10004001": "Failed to configure the RAID controller card. Possible cause: Incorrect parameter or configuration failed.",
        "deploy.error.10004003": "Drives are not consistent with configured Array.",
        "deploy.error.10040011": "Mix of configured and unconfigured drives are not possible.",
        "deploy.error.10040012": "A physical disk does not exist.",
        "deploy.error.10040013": "Drive is too small for requested operation.",
        "deploy.error.10040030": "Configure Adapter Failed.",

        "deploy.error.10400256": "Clear exist configuration failed.",
        "deploy.error.10400257": "Virtual Drive Does not Exist.",
        "deploy.error.10400258": "Config result check failed.",
        "deploy.error.10400259": "RAID controller type mismatch.",

        "deploy.error.10003001": "Incorrect parameter or configuration failed.",
        "deploy.error.10030064": "The personality is invalid or not supported on this adapter.",
        "deploy.error.10030091": "WWN Management: the supplied WWNs ALREADY EXIST.",
        "deploy.error.10300251": "Hardware or firmware does not support command.",
        "deploy.error.10300255": "Invalid format for World Wide Port Name or MAC Address.",
        "deploy.error.10300300": "Can not find CNA card or type is incorrectness.",
        "deploy.error.10300301": "Can not find HBA card or type is incorrectness.",
        "deploy.error.10300302": "CNA card config bandwidth error.",
        "deploy.error.10300303": "CNA card only PF2 can be FCoE or iSCSI.",
        "deploy.error.10300304": "CNA card one port must contains 4 PF nodes.",
        "deploy.error.10300310": "Failed to configure the CNA. Possible cause: The CNA is installed in an incorrect slot, the CPU or memory configuration is incorrect, or the CNA firmware version is incompatible.",

        "deploy.error.10300320": "HBA card config error.",
        "deploy.error.10300400": "CNA card config bandwidth not equal to 100.",
        "deploy.error.10300401": "CNA card NIC PF vlan id not between 2 and 409</br>4.",

        "deploy.error.150100": "Database operation failed.",

        "deploy.error.150101": "Invalid parameter value.",

        "deploy.error.150102": "Nonexistent object.",

        "deploy.error.150103": "The software source is in use.",

        "deploy.error.150104": "Failed to delete the file.",

        "deploy.error.150105": "The software source is not ready. Please wait until the software source production is complete.",

        "deploy.error.148920": "Failed to stop the task.",

        "deploy.error.148921": "Partially succeeded in stopping the task.",

        "deploy.error.148910": "Incorrect task status.",

        "deploy.error.601": "Suspend task failed, task is running.",

        "deploy.error.53701": "Failed to upload softsource\u3002",
        "deploy.error.53702": "The target is not exist\u3002",
        "deploy.error.53703": "The softsource parameters is not correctly\u3002",
        "deploy.error.53704": "Add softsource failed,Mybe because the DB error\u3002",
        "deploy.error.56008": "Task status is not suspend. only suspend task can be resumed.",
        "deploy.error.56009": "Task status is not idle. only idle task can be suspended.",

        "deploy.error.145001": "The software to be deployed does not exist.",
        "deploy.error.145002": "Failed to obtain the device IP address. Check the server management protocol configuration.",
        "deploy.error.145003": "Failed to invoke the add-in.",
        "deploy.error.460": "Failed to generate the configuration result.",
        "deploy.error.2003": "Failed to install the software. Possible cause: The installation script failed to execute.",
        "deploy.error.145004": "Configuration timed out. Possible cause: The software installation failed, or was not complete because the template installation time is short.",
        "deploy.error.145005": "Failed to query the management protocol. Check the server management protocol configuration.",
        "deploy.error.145006": "The HostAgent add-in does not exist.",
        "deploy.error.145007": "Failed to invoke the add-in.",
        "deploy.error.145008 ": "Software configuration failed.",
        "deploy.error.145009": "The time to install the software is not enough\u3002",
        "deploy.error.13087": "Failed to connect SFTP server.",
        "deploy.error.13088": "The Agent failed to install the SFTP client.",
        "deploy.error.13089": "The Agent failed to install the SFTP client.",
        "deploy.error.13090": "Failed to connect to the SFTP server. Possible cause: The SFTP service on eSight had not started.",
        "deploy.error.13091": "The Agent failed to install the SFTP client.",
        "deploy.error.13092": "Failed to create the directory. Possible cause: The HostAgent has no file permission.",
        "deploy.error.13097": "Failed to download the file. Possible cause: </br>1. The SFTP service on eSight had not started. </br>2. The communication between the device and eSight is abnormal. Check the network configurations.",
        "deploy.error.13108": "Failed to install software.",
        "deploy.error.13112": "Failed to install software.",
        "deploy.error.13109": "The software to be deployed does not exist.",
        "deploy.error.13113": "Insufficient free space. The space required for installing the software package exceeded the free space of the system.",
        "deploy.error.13114": "The software to be deployed already exists on the device. Find it under the software_deploy directory.",

        "deploy.error.150200": "Failed to connect to the virtual media. Possible causes: </br>1. The server cannot be connected. </br>2. The link to the server virtual media has been occupied. </br>3. The SNMP v3 protocol is not used by rack servers and high-density servers in VMM encryption. </br>4. The firmware version is too early to support this function.",
        "deploy.error.150201": "Failed to connect to the virtual media. Possible causes: </br>1. The server cannot be connected. </br>2. The link to the server virtual media has been occupied. </br>3. The SNMP v3 protocol is not used by rack servers and high-density servers in VMM encryption. </br>4. The firmware version is too early to support this function.",
        "deploy.error.150202": "Failed to connect to the virtual media. Possible causes: </br>1. The server cannot be connected. </br>2. The link to the server virtual media has been occupied. </br>3. The SNMP v3 protocol is not used by rack servers and high-density servers in VMM encryption. </br>4. The firmware version is too early to support this function.",

        "deploy.error.160000": "Max file size is 10MB.",
        "deploy.error.160001": "File format must be xml or cfg.",
        "deploy.error.160002": "Parameter error.",

        "deploy.error.150431": "Failed to execute the configuration command.",
        "deploy.error.150430": "Failed to connect to the device. Possible cause: Incorrect username or password, or the connection timed out.",

        "deploy.error.0": "Deployment succeeded.",
        "deploy.error.150500": "Failed to connect to the device. Possible cause: The device does not exist.",
        "deploy.error.150501": "Failed to connect to the device. Possible cause: The device is offline.",

        "deploy.error.150502": "Failed to connect to the device. Possible cause: The device is busy.",
        "deploy.error.150503": "Failed to connect to the device. Possible cause: Incorrect username or password, or the connection timed out.",
        "deploy.error.150504": "Failed to execute the command.",
        "deploy.error.150505": "Failed to perform the task. The device is not stacked.",
        "deploy.error.150506": "Failed to perform the task. The device cannot be locked.",
        "deploy.error.150510": "Task deployment failed.",
        "deploy.error.150511": "No response to the delivered command.",

        "deploy.error.150512": "Switchboard configuration failed due to timeout.",

        "deploy.error.150000": "No matched switchboards for stacking.",
        "deploy.error.150001": "Unmatched models of switchboards for stacking.",
        "deploy.error.150002": "Failed to stack the switchboards. Possible cause: The switchboards failed to restart.",
        "deploy.error.150003": "Failed to communicate with the FC plane of the switchboard. Possible cause: </br>1. The FC plane parameters are incorrectly configured on the Switchboard Protocol Parameters page of the server. </br>2. The communication with the FC plane of the switchboard is abnormal.",
        "deploy.error.150004": "Failed to configure the stack domain. Possible cause: Other configurations or operations are performed on the switchboard during the deployment process.",
        "deploy.error.150005": "Failed to restart the switchboard. Possible cause: Other configurations or operations are performed on the switchboard during the deployment process.",
        "deploy.error.150006": "Failed to deliver the command for stack creation.",
        "deploy.error.150007": "Failed to deliver the command for adding physical ports to a port stack. Possible cause: The physical ports have been used by other services.",
        "deploy.error.150008": "Failed to view the stack. Possible cause: Other configurations or operations are performed on the switchboard during the deployment process.",
        "deploy.error.150009": "Failed to save the current settings. Possible cause: Other configurations or operations are performed on the switchboard during the deployment process.",
        "deploy.error.150010": "Failed to configure FCoE parameters for the Fabric plane. Possible cause: Other configurations or operations are performed on the switchboard during the deployment process. ",
        "deploy.error.149202": "The selected device cannot be stacked.",
        "deploy.error.150011": "Failed to configure FCoE parameters for the FC plane. Possible cause: Other configurations or operations are performed on the switchboard during the deployment process. ",
        "deploy.error.150012": "The delivery of VLAN and custom configurations timed out. Possible cause: </br>1. The communication between the switchboard and eSight is abnormal. </br>2. Other configurations or operations are performed on the switchboard during the deployment process. ",
        "deploy.error.150013": "  Failed to create a stack for the switchboards. Possible cause: </br>1. The physical ports configured in the template are not directly connected. </br>2. Other configurations or operations are performed on the switchboard during the deployment process.",
        "deploy.error.150016": "  Failed to create a stack. To stack CX111 or CX915 switchboards, select physical ports for the stack when creating a template.",

        "deploy.error.150300": "ServiceCD does not exist or the file name is not correct.",
        "deploy.error.150301": "Failed to mount ServiceCD. Possible causes: </br>1. The server cannot be connected. </br>2. The link to the server virtual media has been occupied. </br>3. The SNMP v3 protocol is not used by rack servers and high-density servers in VMM encryption. </br>4. The firmware version is too early to support this function.",
        "deploy.error.150302": "ServiceCD mount timed out. Possible cause: Failed to connect to the server due to network anomaly.",
        "deploy.error.150303": "Failed to disconnect from ServiceCD. Possible cause: Failed to connect to the server due to network anomaly.",
        "deploy.error.150304": "Failed to mount the OS. Possible causes: </br>1. The server cannot be connected. </br>2. The link to the server virtual media has been occupied. </br>3. The SNMP v3 protocol is not used by rack servers and high-density servers in VMM encryption. </br>4. The firmware version is too early to support this function.",
        "deploy.error.150305": "Failed to deliver the operating system installation command. Possible cause: Failed to connect to the server due to network anomaly.",
        "deploy.error.150306": "Failed to query the operating system installation progress. Possible cause: Failed to connect to the server due to network anomaly.",
        "deploy.error.150307": "Operating system installation timed out. Possible cause: Failed to connect to the server due to network anomaly.",
        "deploy.error.150308": "Failed to disconnect from the software source. Possible cause: Failed to connect to the server due to network anomaly.",
        "deploy.error.150309": "Failed to deploy the operating system.",
        "deploy.error.150310": "Failed to deploy the operating system. The configuration file template does not exist.",
        "deploy.error.150311": "Failed to deploy the operating system. The installation configuration file was not generated.",
        "deploy.error.150312": "Failed to deliver the configuration information. Possible causes: The delivery is interrupted by other operations or network anomalies occur.",

        "deploy.error.170101": "ServiceCD failed to read SystemInfo.",
        "deploy.error.170102": "ServiceCD failed to read the operating system type.",
        "deploy.error.170103": "Incorrect system installation parameters.",
        "deploy.error.170104": "Failed to copy the driver and configuration file.",
        "deploy.error.170105": "ServiceCD cannot read the operating system configuration parameters.",
        "deploy.error.170106": "The operating system configuration parameter cannot be blank.",
        "deploy.error.170107": "ServiceCD failed to save the configuration information.",
        "deploy.error.170108": "ServiceCD failed to find the operating system CD-ROM.",
        "deploy.error.170109": "Failed to read the configuration file from the CD-ROM.",
        "deploy.error.170110": "Failed to obtain the device SN.",
        "deploy.error.170111": "Failed to read disk information. Possible cause: No available disks.",
        "deploy.error.170112": "ServiceCD cannot read the operating system configuration parameters.",
        "deploy.error.170113": "Failed to detect the system CD-ROM.",
        "deploy.error.170114": "Set boot order failed.",
        "deploy.error.170115": "The size of the partition set in the template is larger than the actual size of the device.",

        "deploy.error.180100": "Failed to change the password because the SFTP service does not exist.",
        "deploy.error.180101": "Failed to change the password because the SFTP user could not be obtained.",
        "deploy.error.180102": "Failed to change the password because the SFTP information could not be obtained.",
        "deploy.error.180103": "Incorrect user name or password.",
        "deploy.error.180104": "The password does not meet requirements.",
        "deploy.error.180105": "The new password must be different from the old password.",
        "deploy.error.180106": "The confirm password must be the same as the password.",
        "deploy.error.180107": "Incorrect passwords are entered for over five times. Wait 15 minutes and retry.",
        "deploy.error.180108": "Failed to update the SFTP service user information.",
        "deploy.error.180109": "The SFTP user already exists.",
        "deploy.error.180110": "Succeeded in changing the upload password.",
        "deploy.error.57000": "The autoinst file is imported successfully.",
        "deploy.error.150313": "The autoinst file does not exist.",
        "deploy.error.150314": "Failed to mount the autoinst folder.",
        "deploy.error.150315": "Failed to obtain the autoinst file using the ServiceCD.",
        "deploy.error.150316": "Invalid autoinst file content.For details, see the generation method in the online help.",
        //------------------模板管理-----------------------

        //------------------固件升级-----------------------
        "firmware.error.200150": "No operation permission.",
        "firmware.error.200100": "The upgrade package description file does not exist.",
        "firmware.error.200101": "Failed to parse the upgrade package description file.",
        "firmware.error.200102": "The module to be upgraded does not support the upgrade.",
        "firmware.error.200103": "No device model is defined in the upgrade package.",
        "firmware.error.200105": "The policy for the firmware to take effect is not supported.",
        "firmware.error.200106": "The verification type of the firmware upgrade file is invalid.",
        "firmware.error.200107": "Failed to verify the firmware upgrade file.",
        "firmware.error.200108": "The firmware upgrade file does not exist.",
        "firmware.error.200109": "Incorrect parameter.",
        "firmware.error.200110": "You are not authorized to delete the upgrade package.",
        "firmware.error.200111": "Failed to delete the upgrade package.",
        "firmware.error.200112": "Failed to decompress the upgrade package.",
        "firmware.error.200113": "Database operation failed.",
        "firmware.error.200114": "No device needs to be upgraded.",
        "firmware.error.200115": "The policy for the firmware to take effect is invalid.",
        "firmware.error.200116": "Incorrect time format.",
        "firmware.error.200117": "Failed to create the task.",
        "firmware.error.200119": "Operation failed.",
        "firmware.error.200120": "The operation is partially successful.",
        "firmware.error.200121": "The operation failed because the task does not exist.",
        "firmware.error.200122": "Operation failed because of incorrect task status. Only a suspended or failed task can be resumed.",
        "firmware.error.200123": "The operation failed because the task is in the executing state.",
        "firmware.error.200124": "The operation failed because the task is in the waiting state.",
        "firmware.error.200125": "The operation failed because the time for the firmware to take effect is incorrect.",
        "firmware.error.200128": "Database operation error.",
        "firmware.error.200130": "The operation object does not exist.",
        "firmware.error.200131": "The operation failed because the task is in the suspended state.",
        "firmware.error.200132": "Failed to lock the device, possible cause: The device is used by other business of eSight. Please try again later.",
        "firmware.error.200133": "Failed to obtain the switchboard version. Possible cause: The switchboard version is too earlier and does not support the upgrade, or the switchboard cannot be connected. Refresh the server where the switchboard resides and retry.",
        "firmware.error.200134": "Operation failed because the task status is incorrect. The task has finished.",
        "firmware.error.200135": "Operation failed because the upgrade package does not exist. Create a new task.",
        "firmware.error.200137": "Deletion failed. The upgrade package is being downloaded.",
        "firmware.error.200140": "Failed to lock the MM, possible cause:the device is upgrading.",
        "firmware.error.300101": "eSight remaining space is insufficient, please clean up disk space.",
        "firmware.error.300102": "Operation failed, the device is busy.",
        "firmware.error.300103": "The size of the upgrade package is larger than 200M.",
        "firmware.error.300104": "Incorrect file type.",
        "firmware.error.300105": "Failed to delete the upgrade file, system internal error.",
        "firmware.error.300106": "Task name must be unique.",
        "firmware.error.300107": "The upgrade package name must be unique.",
        "firmware.error.300108": "The device does not exist. Possible cause: The device has been deleted and added again.",
        "firmware.error.300109": "Upgrade failed,reset HMM failed.",
        "firmware.error.300110": "Upgrade failed,reset BMC failed.",
        "firmware.error.300111": "Upgrade failed,reset server failed.",
        "firmware.error.300112": "The length of the upgrade file name is longer than 128.",
        "firmware.error.300113": "Upgrade failed. Failed to restart the switchboard.",
        "firmware.error.300201": "An automatic firmware upgrade task is being executed. Please try again later.",
        //#\u56fa\u4ef6\u5347\u7ea7\u9519\u8bef\u7801\u5b9a\u4e49",
        "firmware.error.1001": "Invalid parameter.",
        "firmware.error.1002": "Failed to connect to the virtual media. Possible cause: The device does not support the connection to the virtual media, the connection to the server failed, the connection to the virtual media has been set up, or the rack server or high-density server supports VMM encryption but SNMPv3 is not used for access. ",
        "firmware.error.1003": "Failed to restart the server.",
        "firmware.error.1004": "Failed to load the SimpleOS.",
        "firmware.error.1005": "Failed to download the configuration tool package.",
        "firmware.error.1006": "Failed to obtain the device type.",
        "firmware.error.1007": "Unknown error.",
        "firmware.error.1008": "Failed to create the directory.",
        "firmware.error.1009": "Failed to generate an .xml configuration file.",
        "firmware.error.1010": "Failed to obtain SFTP parameters.",
        "firmware.error.1011": "The configuration tool package failed to perform the upgrade operation.",
        "firmware.error.2001": "Failed to download the upgrade file.",
        "firmware.error.2002": "Upgrade failed. Possible cause: The device or enclosure is busy. There are other upgrade tasks in progress.",
        "firmware.error.1100": "Failed to upload the upgrade file. Possible cause: A network exception occurred, management user authentication failed, or the cache capacity is insufficient.",
        "firmware.error.3001": "Failed to upload the upgrade file. Please modify the SNMP template to use SNMPv3 for communication.",
        "firmware.error.1200": "Upgrade failed.",
        "firmware.error.1201": "Failed to deliver the upgrade command. Possible cause: A network exception occurred.",
        "firmware.error.1202": "Upgrade failed because the device failed to start the upgrade.",
        "firmware.error.1203": "Upgrade failed, the current version of the device is the same as the target version.",
        "firmware.error.1204": "Upgrade failed, the upgrade file does not exist.",
        "firmware.error.1205": "Upgrade failed, the upgrade file is incorrect.",
        "firmware.error.1206": "Upgrade failed, the device to be upgraded has insufficient memory capacity.",
        "firmware.error.1207": "Upgrade failed, data is being synchronized to the standby area or data consistency between the active area and the standby area is being checked.",
        "firmware.error.1208": "Upgrade failed, the service system is being powered on, and does not support the upgrade.",
        "firmware.error.1209": "Upgrade failed, failed to download the file.",
        "firmware.error.1210": "Upgrade failed, the upgrade program is running.",
        "firmware.error.1211": "Upgrade failed, the current device can not support the BIOS upgrade when the it is powered on. ",
        "firmware.error.1212": "Upgrade failed. The upgrade file name has been used. If an upgrade file has been used in a fabric plane upgrade, the file name in the next upgrade must be different from that used this time.",
        "firmware.error.1213": "Upgrade failed, the upgrade response timed out.",
        "firmware.error.1214": "Upgrade failed, the upgrade directory has insufficient space.",
        "firmware.error.1218": "Upgrade failed. Cannot obtain the upgrade progress.",
        "firmware.error.-1": "Upgrade failed. Possible cause: A network exception occurred or eSight restarted during the upgrade.",
        "firmware.error.0": "Upgrade succeed.",
        "firmware.error.300301": "No available upgrade package.",
        "firmware.error.300302": "The device is a standby or slave board for stacking.",
        "firmware.error.300303": "No matching driver package is available, or the hardware does not respond.",
        "firmware.error.300304": "Device communication failed. Possible causes\: network exception; incorrect SNMP user name or password; non\u2013SNMP v3 protocol.",
        "firmware.error.300401": "Driver upgrade error\: No response from the BMC or BMA\.Possible cause\: Incorrect protocol parameters\.Device restart abnormal.network disconnection.",
        "firmware.error.300402": "Driver upgrade error\: Driver file upload failure\.Possible cause\: Incorrect protocol parameters\.Device restart abnormal.network disconnection.",
        "firmware.error.300403": "Driver upgrade error\: Script execution failure\.Possible cause\: Incorrect protocol parameters\.Device restart abnormal.network disconnection.",
        "firmware.error.300404": "Driver upgrade error\: Incorrect upgrade file.",
        "firmware.error.300501": "Baseline package upgrade error: Download failure occurred during the baseline package upgrade.",
        "firmware.error.300502": "Baseline package upgrade error: The download tool does not return the download progress.",
        "firmware.error.300503": "Baseline package upgrade error: Failed to copy files.",
        //#createTask Eroor Code",
        "firmware.error.20010901": "Invalid task name.",
        "firmware.error.20010902": "Invalid task description.",
        "firmware.error.20010903": "The task upgrade time policy or time format is incorrect.",
        "firmware.error.20010904": "Incorrect upgrade firmware.",
        "firmware.error.20010905": "Incorrect effective mode.",
        "firmware.error.20010906": "Incorrect upgrade policy.",
        "firmware.error.20010907": "Incorrect baseline package.",
        "firmware.error.20010908": "Incorrect upgrade device.",
        "firmware.error.20010909": "The number of upgrade devices exceeds the system limit.",
        "firmware.error.20010910": "The firmware or driver upgrade package of the same device in a non-associated baseline package cannot be duplicated. ",
        "firmware.error.20010911": "No upgrade item is available to certain devices. Possible causes\: The selected devices are not supported by the selected firmware upgrade package; No upgrade package is available to the firmware to be upgraded.",
        //############\u57fa\u7ebf\u5305\u7ba1\u7406##############",
        "firmware.error.200150": "The current user has no permission to perform the operation.",
        "firmware.error.200000": "Succeeded in uploading the baseline package. ",
        "firmware.error.200001": "Failed to upload the baseline package: Invalid parameter.",
        "firmware.error.200002": "Failed to upload the baseline package: A baseline package with the same name already exists",
        "firmware.error.200003": "Failed to upload the baseline package: The size of the uploaded file exceeds 5 GB.",
        "firmware.error.200004": "Failed to upload the baseline package: Creating the parent directory failed",
        "firmware.error.200005": "Failed to upload the baseline package: File saving error.",
        "firmware.error.200006": "Failed to upload the baseline package: File size verification error.",
        "firmware.error.200007": "Failed to upload the baseline package: Incomplete file content is uploaded.",
        "firmware.error.200008": "Failed to upload the baseline package: The remaining space in eSight is less than 5 GB.",
        "firmware.error.200009": "Failed to upload the baseline package: Invalid file type.",
        "firmware.error.200010": "Failed to cancel the baseline package: upload.",
        "firmware.error.200100": "Failed to upload the baseline package: The upgrade package description file does not exist.",
        "firmware.error.200112": "Failed to upload the baseline package: Failed to decompress the upgrade package.",
        "firmware.error.200999": "Unknown error.",
        "firmware.error.300200": "Failed to upload the baseline package: XML file format is not correct.",
        "firmware.error.300504": "Failed to create directory.",
        "firmware.error.200141": "Some devices have been associated with baseline package or the device does not exist..",
        "firmware.error.300505": "Download condition is empty/ Please select at least one record.",
        "firmware.error.300506": "Failed to download the baseline package: Failed to call the tool.",
        "firmware.error.300507": "Failed to download the baseline package: Failed to query the progress.",
        "firmware.error.300508": "Failed to download the baseline package: Failed to copy file.",
        "firmware.error.53101": "Upload FMwaresource is not end.",
        "firmware.error.500005": "Task of upload FMwaresource created success.",
        "firmware.error.500006": "Upload FMwaresource taskAPIName  isEmpty.",
        "firmware.error.500007": "Device is not exist or device type error.",
        "firmware.error.-2": "Other exception\. THE CMC or iBMC restart is not completed.",
        "firmware.error.-3": "Upgrade failed because the source version is the same as the target version.",
        "firmware.error.-4": "Upgrade failed because the upgrade file does not exist.",
        "firmware.error.-5": "Upgrade file error\. THE CMC or iBMC restart is not completed.",
        "firmware.error.-6": "The KunLun server has insufficient memory capacity.",
        "firmware.error.-7": "Active-standby consistency check in progress\u2026\:THE CMC restart not completed.",
        "firmware.error.-8": "The service system is powered on/ and does not support the upgrade.",
        "firmware.error.-9": "Upgrade is not supported.",
        "firmware.error.-11": "File transfer failed\.Possible cause\:THE iBMC or CMC restart not completed.",
        "firmware.error.-12": "The upgrade program is running.",
        "firmware.error.-13": "Upgrade package file name conflict.",
        "firmware.error.-14": "Response timed out.",
        "firmware.error.-15": "The upgrade directory has insufficient space.",
        "firmware.error.-17": "LCD firmware absent.",
        "firmware.error.-19": "Upgrading the active CMC failed because the active and standby CMCs are both present.",
        "firmware.error.-20": "The service system is powered on/ does not support the upgrade.",
        "firmware.error.4001": "Incorrect upgrade command parameter.",
        "firmware.error.4002": "Failed to send the upgrade command\. Possible cause\: Incorrect protocol parameters\.Device restart abnormal\.network disconnection.",
        "firmware.error.4003": "Failed to enable SSH or query SSH status error\. Possible cause\s: Incorrect protocol parameters\.Device restart abnormal\.network disconnection.",
        "firmware.error.4004": "Failed to power off the device\. Possible cause\: Incorrect protocol parameters\.Device restart abnormal\.network disconnection.",
        "firmware.error.4005": "Failed to restart the device or firmware absent.",
        "firmware.error.4006": "Progress query error\. Possible cause\: Incorrect protocol parameters\.Device restart abnormal\.network disconnection.",
        "firmware.error.4007": "Progress query timed out\. Possible cause\: Incorrect protocol parameters\.Device restart abnormal\.network disconnection.",
        "firmware.error.4008": "Query failed\. Possible cause\: Incorrect protocol parameters\.Device restart abnormal\.network disconnection.",
        "firmware.error.4009": "Failed to start the upgrade.",
        "firmware.error.-10": "The KunLun Device Upgrade is not supported.",
        "firmware.error.-16": "The KunLun Device Upgrade is not supported.",
        "firmware.error.-18": "The KunLun Device Upgrade is not supported."
            //------------------固件升级-----------------------


    }
    /**
     * 获取错误代码
     * @param  errorCode 
     * @returns  errorMsg
     */
function getErrorMsg(errorCode) {
    var lang = localStorage.getItem('lang');
    if (lang === 'en') {
        if (errorCode_en[errorCode]) {
            return errorCode_en[errorCode];
        }
        return errorCode;

    } else {
        if (errorCode_zh_CN[errorCode]) {
            return errorCode_zh_CN[errorCode];
        }
        return errorCode;
    }

};